package com.degraffa.mcdnd.character;

public enum Proficiency {
    LightArmor,
    MediumArmor,
    HeavyArmor,
    Shields,
    SimpleWeapons,
    MartialWeapons,
    ThievesTools,
    TinkersTools,
    ArtisansTools,
    SkillAcrobatics,
    SkillAnimalHandling,
    SkillArcana,
    SkillAthletics,
    SkillDeception,
    SkillHistory,
    SkillInsight,
    SkillIntimidation,
    SkillInvestigation,
    SkillMedicine,
    SkillNature,
    SkillPerception,
    SkillPerformance,
    SkillPersuasion,
    SkillReligion,
    SkillSleightOfHand,
    SkillStealth,
    SkillSurvival,
    StrengthSave,
    DexSave,
    ConSave,
    WisSave,
    IntSave,
    CharismaSave
}
