name: minecraft-dnd
version: 1.0.0
main: com.degraffa.mcdnd.MCDnD
api-version: "1.16"
commands:
  roll:
    description: Rolls a specified dice roll using d20 notation.
    usage: "Usage: /roll <dice notation>"
    permission: mcdnd.roll
    permission-message: You do not have permission to roll!
  rollme:
    description: Like roll, but the results are only sent to you
    usage: "Usage: /rollme <dice notation>"
    permission: mcdnd.roll
    permission-message: You do not have permission to roll!
  rollto:
    description: Like roll, but the results are only sent to you and to another user
    usage: "Usage: /rollme <username> <dice notation>"
    permission: mcdnd.roll
    permission-message: You do not have permission to roll!
  rolldm:
    description: Like roll, but the results are only sent to you and DMs
    usage: "Usage: /rolldm <dice notation>"
    permission: mcdnd.roll
    permission-message: You do not have permission to roll!